const REASONS_DATA = [
  {
    roman: "I",
    title: "Who You Are",
    items: [
      { n: 1, t: "Your kindness." },
      { n: 2, t: "Your intelligence." },
      { n: 3, t: "Our same humor." },
      { n: 4, t: "Your laugh." },
      { n: 5, t: "Your smile." },
      { n: 6, t: 'Your "ngii."' },
      { n: 7, t: 'Your "lah."' },
      { n: 8, t: "Your nyenyenye." },
      { n: 9, t: "Your organized brain." },
      { n: 10, t: "Your OC side." },
      { n: 11, t: "Your outgoing personality." },
      { n: 12, t: "Your independent side." },
      { n: 13, t: "Your clingy side with me." },
      { n: 14, t: "Your serious side." },
      { n: 15, t: "Your dramatic side." },
      { n: 16, t: "Your competitive side." },
      { n: 17, t: "Your stubbornness." },
      { n: 18, t: "Your patience." },
      { n: 19, t: "Your protectiveness." },
      { n: 20, t: "Your affection." },
      { n: 21, t: "Your honesty." },
      { n: 22, t: "Your loyalty." },
      { n: 23, t: "Your determination." },
      { n: 24, t: "Your hard work." },
      { n: 25, t: "Your ambition." },
      { n: 26, t: "Your courage." },
      { n: 27, t: "Your confidence." },
      { n: 28, t: "Your curiosity." },
      { n: 29, t: "Your creativity." },
      { n: 30, t: "Your thoughtful nature." },
    ],
  },
  {
    roman: "II",
    title: "What You Love",
    items: [
      { n: 31, t: "Your love for family." },
      { n: 32, t: "Your big dreams." },
      { n: 33, t: "Your civil-engineer dreams." },
      { n: 34, t: "Your future plans." },
      { n: 35, t: "Your dream of being rich." },
      { n: 36, t: "Your dream of two kids." },
      { n: 37, t: "Your love for matcha." },
      { n: 38, t: "Your iced matcha lattes." },
      { n: 39, t: "Your takoyaki obsession." },
      { n: 40, t: "Your Ilocos empanada." },
      { n: 41, t: "Your soggy fries." },
      { n: 42, t: "Your Potcor orders." },
      { n: 43, t: "Your love for pink." },
      { n: 44, t: "Your dark-red aesthetic." },
      { n: 45, t: "Your all-black outfits." },
      { n: 46, t: "Especially matching mine." },
      { n: 47, t: "Your love for peonies." },
      { n: 48, t: "Your love for lilies." },
      { n: 49, t: "Your love for roses." },
      { n: 50, t: "Your love for cats." },
      { n: 51, t: "Your love for golden retrievers." },
      { n: 52, t: "Your love for Iron Man." },
      { n: 53, t: "Your love for Moana." },
      { n: 54, t: "Your Reyna main era." },
      { n: 55, t: "Your Roblox side." },
      { n: 56, t: "Your love for AUs." },
      { n: 57, t: "Your love for rainy weather." },
      { n: 58, t: "Your love for sunsets." },
      { n: 59, t: "Your love for beaches." },
      { n: 60, t: "Your love for photobooths." },
      { n: 61, t: "Your love for letters." },
      { n: 62, t: "Your love for flowers." },
    ],
  },
  {
    roman: "III",
    title: "How We Talk",
    items: [
      { n: 63, t: "Your appreciation for effort." },
      { n: 64, t: "Your appreciation for thoughtful surprises." },
      { n: 65, t: "Your excitement over unexpected websites." },
      { n: 66, t: "Your reactions to my websites." },
      { n: 67, t: "Your long conversations." },
      { n: 68, t: "Our VCs." },
      { n: 69, t: "Your reassuring messages." },
      { n: 70, t: "Your ability to open up." },
      { n: 71, t: "My ability to open up to you." },
      { n: 72, t: "Our honesty." },
      { n: 73, t: "Our trust." },
      { n: 74, t: "Our understanding." },
      { n: 75, t: "Our communication." },
      { n: 76, t: "Our shared jokes." },
      { n: 77, t: "Our random jokes." },
      { n: 78, t: "Our stupid jokes." },
      { n: 79, t: "Our inside jokes." },
      { n: 80, t: "Our matching humor." },
      { n: 81, t: "Understanding each other's jokes." },
      { n: 82, t: "Laughing at the same things." },
      { n: 83, t: "Thinking the same thing." },
      { n: 84, t: "Just by looking at each other." },
      { n: 85, t: "Our comfortable silence." },
      { n: 86, t: "Our random conversations." },
      { n: 87, t: "Our serious conversations." },
      { n: 88, t: "Our deep conversations." },
      { n: 89, t: "Our ridiculous conversations." },
      { n: 90, t: "How quickly we switch topics." },
      { n: 91, t: "How easily we talk." },
      { n: 92, t: "How we can be ourselves." },
      { n: 93, t: "How we can be vulnerable." },
      { n: 94, t: "How we can admit things." },
      { n: 95, t: "How we can listen." },
      { n: 96, t: "How we can reassure each other." },
      { n: 97, t: "How we can talk things through." },
      { n: 98, t: "How you come to me when things get hard." },
      { n: 99, t: "How you trust me." },
      { n: 100, t: "How you let me be there for you." },
    ],
  },
  {
    roman: "IV",
    title: "How You Keep Going",
    items: [
      { n: 101, t: "How you keep trying." },
      { n: 102, t: "How you don't give up." },
      { n: 103, t: "How hardworking you are." },
      { n: 104, t: "How you underestimate yourself." },
      { n: 105, t: "How much you actually accomplish." },
      { n: 106, t: "How much potential you have." },
      { n: 107, t: "How smart you actually are." },
      { n: 108, t: "How much you care about school." },
      { n: 109, t: "How seriously you take your future." },
      { n: 110, t: "How determined you are to become an engineer." },
      { n: 111, t: "How proud you'll be as a civil engineer." },
      { n: 112, t: "How you dream big." },
      { n: 113, t: "How you keep moving forward." },
      { n: 114, t: "How you handle difficult days." },
      { n: 115, t: "How you seek support when needed." },
      { n: 116, t: "How you keep your heart open." },
      { n: 117, t: "How much you care." },
      { n: 118, t: "How deeply you care." },
      { n: 119, t: "How you remember little things." },
      { n: 120, t: "How you notice details." },
      { n: 121, t: "How you appreciate effort." },
      { n: 122, t: "How you appreciate sincerity." },
      { n: 123, t: "How you value meaningful gestures." },
      { n: 124, t: "How letters matter to you." },
      { n: 125, t: "How flowers matter to you." },
      { n: 126, t: "How little surprises matter." },
      { n: 127, t: "How handmade things matter." },
      { n: 128, t: "How thoughtful things matter." },
      { n: 129, t: "How you make effort feel worthwhile." },
      { n: 130, t: "How you make ordinary moments memorable." },
    ],
  },
  {
    roman: "V",
    title: "Little Things I Notice",
    items: [
      { n: 131, t: "Our photobooth memories." },
      { n: 132, t: "Meeting my parents." },
      { n: 133, t: "Holding hands at church." },
      { n: 134, t: "Our first meeting." },
      { n: 135, t: "Wishing we'd done more that day." },
      { n: 136, t: "You dodging our first kiss." },
      { n: 137, t: "That awkward moment." },
      { n: 138, t: "That funny memory." },
      { n: 139, t: "The memories we've collected." },
      { n: 140, t: "The memories still waiting for us." },
      { n: 141, t: "Your smile after something funny." },
      { n: 142, t: "Your laugh when you can't hold it." },
      { n: 143, t: "Your random expressions." },
      { n: 144, t: "Your little reactions." },
      { n: 145, t: "Your excited reactions." },
      { n: 146, t: "Your embarrassed reactions." },
      { n: 147, t: 'Your "ngii."' },
      { n: 148, t: 'Your "lah."' },
      { n: 149, t: "Your nyenyenye." },
      { n: 150, t: "Your angry typing." },
      { n: 151, t: "Your lack of shortcuts when you're normal." },
      { n: 152, t: "Knowing you're mad when you suddenly use shortcuts." },
      { n: 153, t: "Your serious voice." },
      { n: 154, t: "Your playful voice." },
      { n: 155, t: "Your VC personality." },
      { n: 156, t: "Your random stories." },
      { n: 157, t: "Your random thoughts." },
      { n: 158, t: "Your random questions." },
      { n: 159, t: "Your unexpected jokes." },
      { n: 160, t: "Your unexpected sweetness." },
      { n: 161, t: "Your unexpected websites." },
      { n: 162, t: "Your appreciation of my effort." },
      { n: 163, t: "Your ability to make me smile." },
      { n: 164, t: "Your ability to make conversations fun." },
      { n: 165, t: "Your ability to make silence comfortable." },
      { n: 166, t: "Your ability to make serious talks easier." },
      { n: 167, t: "Your ability to make difficult days lighter." },
      { n: 168, t: "Your ability to make ordinary things memorable." },
      { n: 169, t: "Your ability to make people feel heard." },
      { n: 170, t: "Your ability to make people feel cared for." },
    ],
  },
  {
    roman: "VI",
    title: "The Person You Are To Others",
    items: [
      { n: 171, t: "Your kindness to people you trust." },
      { n: 172, t: "Your loyalty to people you love." },
      { n: 173, t: "Your protective nature." },
      { n: 174, t: "Your affectionate nature." },
      { n: 175, t: "Your patient nature." },
      { n: 176, t: "Your thoughtful nature." },
      { n: 177, t: "Your hardworking nature." },
      { n: 178, t: "Your determined nature." },
      { n: 179, t: "Your ambitious nature." },
      { n: 180, t: "Your genuine nature." },
      { n: 181, t: "Your unique personality." },
      { n: 182, t: "Your individuality." },
      { n: 183, t: "Your confidence." },
      { n: 184, t: "Your independence." },
      { n: 185, t: "Your willingness to learn." },
      { n: 186, t: "Your willingness to grow." },
      { n: 187, t: "Your ability to admit things." },
      { n: 188, t: "Your ability to communicate." },
      { n: 189, t: "Your ability to listen." },
      { n: 190, t: "Your ability to understand." },
      { n: 191, t: "Your ability to forgive." },
      { n: 192, t: "Your ability to keep trying." },
      { n: 193, t: "Your ability to care." },
      { n: 194, t: "Your ability to love deeply." },
      { n: 195, t: "Your ability to make people laugh." },
      { n: 196, t: "Your ability to make memories." },
      { n: 197, t: "Your ability to turn moments into stories." },
      { n: 198, t: "Your ability to make things meaningful." },
      { n: 199, t: "Your ability to stay genuine." },
      { n: 200, t: "Your ability to be yourself." },
    ],
  },
  {
    roman: "VII",
    title: "Facts, Officially",
    items: [
      { n: 201, t: "Matcha runs in your veins." },
      { n: 202, t: "Potcor deserves its own food group." },
      { n: 203, t: "Soggy fries somehow make sense to you." },
      { n: 204, t: "Takoyaki is always a good idea to you." },
      { n: 205, t: "Ilocos empanada never disappoints." },
      { n: 206, t: "Iced matcha latte supremacy." },
      { n: 207, t: "Pink looks like your personality." },
      { n: 208, t: "Dark red fits your vibe." },
      { n: 209, t: "All-black outfits are your uniform." },
      { n: 210, t: "Matching black outfits are even better." },
      { n: 211, t: "Peonies are basically your flowers." },
      { n: 212, t: "Lilies are basically your flowers." },
      { n: 213, t: "Roses are basically your flowers." },
      { n: 214, t: "Cats are your tiny kingdom." },
      { n: 215, t: "Golden retrievers have your approval." },
      { n: 216, t: "Iron Man has your approval." },
      { n: 217, t: "Moana has your approval." },
      { n: 218, t: "Reyna has your Valorant approval." },
      { n: 219, t: "Roblox has your attention." },
      { n: 220, t: "AUs have your attention." },
      { n: 221, t: "Rain has your approval." },
      { n: 222, t: "Sunsets have your approval." },
      { n: 223, t: "Beaches have your approval." },
      { n: 224, t: "Photobooths have your approval." },
      { n: 225, t: "Letters have your approval." },
      { n: 226, t: "Flowers have your approval." },
      { n: 227, t: "Sweet websites have your approval." },
      { n: 228, t: "Long messages have your approval." },
      { n: 229, t: "Reassurance has your approval." },
      { n: 230, t: "Being there matters to you." },
    ],
  },
  {
    roman: "VIII",
    title: "What You Value",
    items: [
      { n: 231, t: "You don't need expensive things to appreciate effort." },
      { n: 232, t: "You notice when someone tries." },
      { n: 233, t: "You remember thoughtful gestures." },
      { n: 234, t: "You value sincerity." },
      { n: 235, t: "You value consistency." },
      { n: 236, t: "You value communication." },
      { n: 237, t: "You value respect." },
      { n: 238, t: "You value trust." },
      { n: 239, t: "You value patience." },
      { n: 240, t: "You value healthy relationships." },
      { n: 241, t: "You care about mutual effort." },
      { n: 242, t: "You care about understanding." },
      { n: 243, t: "You care about honesty." },
      { n: 244, t: "You care about growth." },
      { n: 245, t: "You care about the future." },
      { n: 246, t: "You care about family." },
      { n: 247, t: "You care about people." },
      { n: 248, t: "You care about the little things." },
      { n: 249, t: "You care about meaningful moments." },
      { n: 250, t: "You care deeply." },
    ],
  },
  {
    roman: "IX",
    title: "Things You Hate (Apparently Me Too)",
    items: [
      { n: 251, t: "You hate sweets." },
      { n: 252, t: "Yet somehow love matcha." },
      { n: 253, t: "You hate bad Valorant teammates." },
      { n: 254, t: "Especially toxic ones." },
      { n: 255, t: "Especially no-aim ones." },
      { n: 256, t: "Especially unlucky games." },
      { n: 257, t: "You hate cigar smoke." },
      { n: 258, t: "You hate crowded places." },
      { n: 259, t: "You hate disrespect." },
      { n: 260, t: "You hate perverts." },
      { n: 261, t: "You hate arrogance." },
      { n: 262, t: "You hate hot weather." },
      { n: 263, t: "You hate people who watch anime." },
      { n: 264, t: "Apparently you hate me too." },
    ],
  },
  {
    roman: "X",
    title: "Somehow, Us",
    items: [
      { n: 265, t: "Somehow I'm still here." },
      { n: 266, t: "Somehow you still talk to me." },
      { n: 267, t: "Somehow you still VC with me." },
      { n: 268, t: "Somehow you still tolerate my nonsense." },
      { n: 269, t: "Somehow you still laugh at my jokes." },
      { n: 270, t: "Probably because our humor matches." },
      { n: 271, t: "Maybe that's why we work." },
      { n: 272, t: "Maybe that's why we understand each other." },
      { n: 273, t: "Maybe that's why we think alike." },
      { n: 274, t: "Maybe that's why one look can be enough." },
      { n: 275, t: "Maybe that's why conversations flow." },
      { n: 276, t: "Maybe that's why silence isn't awkward." },
      { n: 277, t: "Maybe that's why we can open up." },
      { n: 278, t: "Maybe that's why you come to me." },
      { n: 279, t: "Maybe that's why I want to be there." },
      { n: 280, t: "Maybe that's why our memories matter." },
    ],
  },
  {
    roman: "XI",
    title: "What You Make Me Feel",
    items: [
      { n: 281, t: "You make being understood feel easy." },
      { n: 282, t: "You make being heard feel natural." },
      { n: 283, t: "You make honesty feel safer." },
      { n: 284, t: "You make conversations meaningful." },
      { n: 285, t: "You make jokes funnier." },
      { n: 286, t: "You make random moments memorable." },
      { n: 287, t: "You make simple gestures meaningful." },
      { n: 288, t: "You make effort worth giving." },
      { n: 289, t: "You make letters worth writing." },
      { n: 290, t: "You make websites worth building." },
      { n: 291, t: "You make flowers worth choosing." },
      { n: 292, t: "You make photobooths worth remembering." },
      { n: 293, t: "You make VCs worth staying for." },
      { n: 294, t: "You make long messages worth writing." },
      { n: 295, t: "You make reassurance worth giving." },
      { n: 296, t: "You make memories worth keeping." },
      { n: 297, t: "You make ordinary days different." },
      { n: 298, t: "You make little things matter." },
      { n: 299, t: "You make moments feel special." },
      { n: 300, t: "You make life more interesting." },
      { n: 301, t: "You make me laugh." },
      { n: 302, t: "You make me think." },
      { n: 303, t: "You make me listen." },
      { n: 304, t: "You make me communicate." },
      { n: 305, t: "You make me appreciate details." },
      { n: 306, t: "You make me remember things." },
      { n: 307, t: "You make me want to create." },
      { n: 308, t: "You make me want to surprise you." },
      { n: 309, t: "You make me want to write." },
      { n: 310, t: "You make me want to improve." },
      { n: 311, t: "You make me want to be present." },
      { n: 312, t: "You make me want to support you." },
      { n: 313, t: "You make me want to see you succeed." },
      { n: 314, t: "You make me want to see you become an engineer." },
      { n: 315, t: "You make me want to see your dreams happen." },
      { n: 316, t: "You make me want to see your future." },
      { n: 317, t: "You make me want to see your smile." },
      { n: 318, t: "You make me want to protect your happiness." },
      { n: 319, t: "You make me appreciate what we have." },
      { n: 320, t: "You make me appreciate you." },
    ],
  },
  {
    roman: "XII",
    title: "What You Deserve, Pt. I",
    items: [
      { n: 321, t: "Your smile is unforgettable." },
      { n: 322, t: "Your laugh is contagious." },
      { n: 323, t: "Your humor is unmatched." },
      { n: 324, t: "Your kindness is obvious." },
      { n: 325, t: "Your intelligence is underrated." },
      { n: 326, t: "Your hard work deserves recognition." },
      { n: 327, t: "Your dreams deserve support." },
      { n: 328, t: "Your future deserves excitement." },
      { n: 329, t: "Your effort deserves appreciation." },
      { n: 330, t: "Your heart deserves kindness." },
      { n: 331, t: "Your mind deserves respect." },
      { n: 332, t: "Your personality deserves appreciation." },
      { n: 333, t: "Your goals deserve cheering." },
      { n: 334, t: "Your successes deserve celebrating." },
      { n: 335, t: "Your struggles deserve understanding." },
      { n: 336, t: "Your bad days deserve patience." },
      { n: 337, t: "Your good days deserve celebration." },
      { n: 338, t: "Your dreams deserve someone who believes." },
      { n: 339, t: "Your smile deserves to be protected." },
      { n: 340, t: "Your happiness matters." },
    ],
  },
  {
    roman: "XIII",
    title: "What You Don't See In Yourself",
    items: [
      { n: 341, t: "You don't give yourself enough credit." },
      { n: 342, t: "You work harder than you realize." },
      { n: 343, t: "You are smarter than you think." },
      { n: 344, t: "You are stronger than you realize." },
      { n: 345, t: "You are more capable than you believe." },
      { n: 346, t: "You keep going." },
      { n: 347, t: "You keep learning." },
      { n: 348, t: "You keep trying." },
      { n: 349, t: "You keep caring." },
      { n: 350, t: "You keep dreaming." },
      { n: 351, t: "You don't give up easily." },
      { n: 352, t: "You seek me when things get hard." },
      { n: 353, t: "You let me support you." },
      { n: 354, t: "You let me listen." },
      { n: 355, t: "You let me reassure you." },
      { n: 356, t: "You let me see the real you." },
      { n: 357, t: "You let me know your worries." },
      { n: 358, t: "You let me know your thoughts." },
      { n: 359, t: "You let me know your feelings." },
      { n: 360, t: "You trust me with pieces of yourself." },
    ],
  },
  {
    roman: "XIV",
    title: "What We Can Do",
    items: [
      { n: 361, t: "We can talk about serious things." },
      { n: 362, t: "We can talk about stupid things." },
      { n: 363, t: "We can laugh about nothing." },
      { n: 364, t: "We can understand without words." },
      { n: 365, t: "We can look at each other and know." },
      { n: 366, t: "We can open up." },
      { n: 367, t: "We can listen." },
      { n: 368, t: "We can reassure." },
      { n: 369, t: "We can communicate." },
      { n: 370, t: "We can grow." },
      { n: 371, t: "We can learn." },
      { n: 372, t: "We can make memories." },
      { n: 373, t: "We can laugh." },
      { n: 374, t: "We can be weird." },
      { n: 375, t: "We can be serious." },
      { n: 376, t: "We can be ourselves." },
      { n: 377, t: "We can be honest." },
      { n: 378, t: "We can be vulnerable." },
      { n: 379, t: "We can be comfortable." },
      { n: 380, t: "We can be us." },
    ],
  },
  {
    roman: "XV",
    title: "Your Future Eras",
    items: [
      { n: 381, t: "Your future civil-engineer era." },
      { n: 382, t: "Your future rich era." },
      { n: 383, t: "Your future two-kids era." },
      { n: 384, t: "Your future beach trips." },
      { n: 385, t: "Your future sunsets." },
      { n: 386, t: "Your future rainy days." },
      { n: 387, t: "Your future matcha runs." },
      { n: 388, t: "Your future photobooths." },
      { n: 389, t: "Your future memories." },
      { n: 390, t: "Your future achievements." },
    ],
  },
  {
    roman: "XVI",
    title: "What I Want For You",
    items: [
      { n: 391, t: "I want to see you graduate." },
      { n: 392, t: "I want to see you succeed." },
      { n: 393, t: "I want to see you become an engineer." },
      { n: 394, t: "I want to see you proud of yourself." },
      { n: 395, t: "I want to see you accomplish your goals." },
      { n: 396, t: "I want to see you happy." },
      { n: 397, t: "I want to see you smile." },
      { n: 398, t: "I want to see you laugh." },
      { n: 399, t: "I want to see you enjoy your life." },
      { n: 400, t: "I want to see you realize how capable you are." },
    ],
  },
  {
    roman: "XVII",
    title: "What You Deserve, Pt. II",
    items: [
      { n: 401, t: "You deserve to be proud of yourself." },
      { n: 402, t: "You deserve to recognize your hard work." },
      { n: 403, t: "You deserve to celebrate your progress." },
      { n: 404, t: "You deserve reassurance." },
      { n: 405, t: "You deserve kindness." },
      { n: 406, t: "You deserve patience." },
      { n: 407, t: "You deserve respect." },
      { n: 408, t: "You deserve honesty." },
      { n: 409, t: "You deserve healthy communication." },
      { n: 410, t: "You deserve people who believe in you." },
      { n: 411, t: "You deserve people who listen." },
      { n: 412, t: "You deserve people who support your dreams." },
      { n: 413, t: "You deserve people who appreciate your effort." },
      { n: 414, t: "You deserve people who notice your smile." },
      { n: 415, t: "You deserve people who appreciate your laugh." },
      { n: 416, t: "You deserve people who understand your humor." },
      { n: 417, t: "You deserve people who respect your boundaries." },
      { n: 418, t: "You deserve people who see your worth." },
      { n: 419, t: "You deserve people who stay genuine." },
      { n: 420, t: "You deserve happiness." },
    ],
  },
  {
    roman: "XVIII",
    title: "Unforgettable, Irreplaceable, You",
    items: [
      { n: 421, t: "Your smile is something I won't take for granted." },
      { n: 422, t: "Your laugh is something I won't forget." },
      { n: 423, t: "Your kindness is something I appreciate." },
      { n: 424, t: "Your hard work is something I admire." },
      { n: 425, t: "Your dreams are something I believe in." },
      { n: 426, t: "Your future is something worth looking forward to." },
      { n: 427, t: "Your personality is impossible to copy." },
      { n: 428, t: "Your humor is impossible to replace." },
      { n: 429, t: "Your little habits make you recognizable." },
      { n: 430, t: "Your random words make you memorable." },
      { n: 431, t: 'Your "ngii" is unforgettable.' },
      { n: 432, t: 'Your "lah" is unforgettable.' },
      { n: 433, t: "Your nyenyenye is unforgettable." },
      { n: 434, t: "Your angry shortcuts are recognizable." },
      { n: 435, t: "Your all-black outfits are recognizable." },
      { n: 436, t: "Your matcha orders are recognizable." },
      { n: 437, t: "Your Potcor orders are recognizable." },
      { n: 438, t: "Your Reyna games are recognizable." },
      { n: 439, t: "Your AU obsession is recognizable." },
      { n: 440, t: "Your love for sunsets is recognizable." },
      { n: 441, t: "Your love for rain is recognizable." },
      { n: 442, t: "Your love for beaches is recognizable." },
      { n: 443, t: "Your love for flowers is recognizable." },
      { n: 444, t: "Your love for letters is recognizable." },
      { n: 445, t: "Your love for thoughtful surprises is recognizable." },
      { n: 446, t: "Your love for meaningful moments is recognizable." },
      { n: 447, t: "Your love for family is recognizable." },
      { n: 448, t: "Your love for your dreams is recognizable." },
      { n: 449, t: "Your love for a healthy relationship is recognizable." },
      { n: 450, t: "Your love for being yourself is recognizable." },
    ],
  },
  {
    roman: "XIX",
    title: "You, Simply",
    items: [
      { n: 451, t: "You are funny." },
      { n: 452, t: "You are kind." },
      { n: 453, t: "You are smart." },
      { n: 454, t: "You are hardworking." },
      { n: 455, t: "You are determined." },
      { n: 456, t: "You are ambitious." },
      { n: 457, t: "You are caring." },
      { n: 458, t: "You are affectionate." },
      { n: 459, t: "You are protective." },
      { n: 460, t: "You are patient." },
      { n: 461, t: "You are organized." },
      { n: 462, t: "You are independent." },
      { n: 463, t: "You are outgoing." },
      { n: 464, t: "You are serious when it matters." },
      { n: 465, t: "You are chaotic when it doesn't." },
      { n: 466, t: "You are competitive." },
      { n: 467, t: "You are stubborn." },
      { n: 468, t: "You are dramatic." },
      { n: 469, t: "You are easily excited." },
      { n: 470, t: "You are genuinely you." },
    ],
  },
  {
    roman: "XX",
    title: "The Ways You Make Me",
    items: [
      { n: 471, t: "You make me laugh." },
      { n: 472, t: "You make me think." },
      { n: 473, t: "You make me appreciate little things." },
      { n: 474, t: "You make memories memorable." },
      { n: 475, t: "You make ordinary things special." },
      { n: 476, t: "You make conversations interesting." },
      { n: 477, t: "You make VCs enjoyable." },
      { n: 478, t: "You make letters meaningful." },
      { n: 479, t: "You make websites worth making." },
      { n: 480, t: "You make flowers worth giving." },
      { n: 481, t: "You make photobooths worth remembering." },
      { n: 482, t: "You make matching outfits fun." },
      { n: 483, t: "You make sunsets better." },
      { n: 484, t: "You make rainy days better." },
      { n: 485, t: "You make beach dreams better." },
      { n: 486, t: "You make matcha more recognizable." },
      { n: 487, t: "You make Potcor more recognizable." },
      { n: 488, t: 'You make "ngii" funny.' },
      { n: 489, t: 'You make "lah" funny.' },
      { n: 490, t: "You make nyenyenye funny." },
      { n: 491, t: "You make inside jokes better." },
      { n: 492, t: "You make serious conversations meaningful." },
      { n: 493, t: "You make opening up easier." },
      { n: 494, t: "You make being there matter." },
      { n: 495, t: "You make effort matter." },
      { n: 496, t: "You make memories matter." },
      { n: 497, t: "You make the future exciting." },
      { n: 498, t: "You make me want to keep creating memories." },
      { n: 499, t: "You are someone I never want to take for granted." },
    ],
  },
  {
    roman: "XXI",
    title: "Reasons 500 & 501",
    items: [
      {
        n: 500,
        t: "500. I love that somehow, after all this, I can still think of more things to appreciate about you..",
      },
      {
        n: 501,
        t: "501. told ya so i love you more than 500 reasons. 😭",
      },
    ],
  },
];
